config/routes.rb
Annotation::Application.routes.draw do
  get 'signup', to: 'users#new',        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
    
  root to: 'snippets#index'
  
  resources :users
  resources :snippets
  resources :sessions
  resources :password_resets
  resources :invitations
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name, :title
  
  has_many :snippets, dependent: :destroy
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :name, :code, :language_id, :user
  belongs_to :language, counter_cache: true
  belongs_to :user, counter_cache: true
  
  validates_presence_of :name, :code, :language
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation

  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email
  validates_confirmation_of :password
  
  has_many :snippets, dependent: :destroy
  before_create { generate_token(:auth_token) }

  has_secure_password
  

private
  def self.generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  respond_to :html
  
  rescue_from ActiveRecord::RecordNotFound do
    case request.format.symbol
    when :html
      redirect_to root_path, flash: {error: t("flash.not_found.alert")} 
    when :json
      render :json => {:error => "Question not found"}, :status => 404
    end
  end
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth = Authentication.new(params)
    if auth.authenticated?
      if params[:remember_me]
        cookies.permanent[:auth_token] = auth.user.auth_token
      else
        cookies[:auth_token] = auth.user.auth_token  
      end
      session[:user_id] = auth.user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:error] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def index
    @snippets = current_user.snippets if current_user
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = current_user.snippets.create(params[:snippet])
    if @snippet.save
      redirect_to @snippet, notice: "Snippet was successfully created."
    else
      render :new
    end
  end

  def edit
    @snippet = Snippet.find(params[:id])
  end

  def update
    @snippet = Snippet.find(params[:id])
    if @snippet.update_attributes(params[:snippet])
      redirect_to @snippet, notice: "Snippet was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy
    redirect_to snippets_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Annotation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <div id="flash_<%= name %>" class="flash_messages">
      <%= msg %>
      <%= link_to "hide", nil, class: "hide" %>
    </div>
  <% end %>
  </div>
  <div id="container">
    <div id="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet do |f| %>
  <% if @snippet.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>
      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.collection_select :language_id, Language.order(:name), :id, :title, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :code, "Source Code" %><br />
    <%= f.text_area :code, rows: 14, cols: 50 %>
  </div>
  <div class="actions">
    <%= f.submit "Post Snippet", class: "btn" %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Edit Snippet</h1>

<%= render "form" %>

app/views/snippets/index.html.erb
<h1>Snippets</h1>


<% if current_user %>
  <% @snippets.each do |snippet| %>
    <div class="snippet">
      <%= link_to snippet.name, snippet %>
    </div>
  <% end %>
<% end %>


<p><%= link_to 'New Snippet', new_snippet_path, class: "btn" %></p>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render "form" %>

app/views/snippets/show.html.erb
<h1><%= @snippet.name %></h1>

<p>
  <strong>Language:</strong>
  <%= @snippet.language.title %>
</p>

<%= raw Pygments.highlight(@snippet.code, lexer: @snippet.language.name) %>

<%= link_to "Edit", edit_snippet_path(@snippet), class: "btn" %>
<%= link_to "New Snippet", new_snippet_path, class: "btn" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>